import Link from 'next/link';
import { Shell } from '@/components/Shell';

export default function NewTransaction() {
  return (
    <Shell active="new">
      <div className="topbar"><div><div className="eyebrow">New transaction · Mock workflow</div><h1>Open the deal workspace.</h1><p className="page-lead">Capture only the known facts. Missing details can be resolved during review.</p></div><span className="status neutral">Step 1 of 1</span></div>
      <div className="new-transaction-layout">
        <form className="card transaction-form">
          <div className="form-block"><span className="section-kicker">Relationship</span><h2>Who are you representing?</h2><div className="field-grid"><label>Client type<select defaultValue="buyer"><option value="buyer">Buyer</option><option value="seller">Seller</option><option value="builder">Builder</option><option value="investor">Investor</option></select></label><label>Representation<select defaultValue="buyer-agent"><option value="buyer-agent">Buyer represented by us</option><option value="seller-agent">Seller represented by us</option><option value="limited-agency">Limited agency</option><option value="unrepresented">Unrepresented party involved</option></select></label></div></div>
          <div className="form-block"><span className="section-kicker">Parties</span><h2>Buyer and seller information</h2><div className="field-grid"><label>Buyer legal name(s)<input defaultValue="Brenton Welker; Emily Welker" /></label><label>Seller name or entity<input placeholder="Unknown — add when confirmed" /></label><label>Primary client email<input type="email" defaultValue="brenton.welker@example.test" /></label><label>Client phone<input type="tel" defaultValue="(555) 014-7283" /></label></div></div>
          <div className="form-block"><span className="section-kicker">Property</span><h2>Property information</h2><div className="field-grid"><label className="field-span-2">Street address<input defaultValue="2948 E Alderann St" /></label><label>City<input defaultValue="St. George" /></label><label>State<select defaultValue="UT"><option value="UT">Utah</option></select></label><label>ZIP code<input defaultValue="84790" /></label><label>Property type<select defaultValue="single-family"><option value="single-family">Single-family</option><option value="condo">Condominium</option><option value="townhome">Townhome</option><option value="land">Land</option><option value="commercial">Commercial</option></select></label></div></div>
          <div className="form-block"><span className="section-kicker">Deal</span><h2>Transaction and financing</h2><div className="field-grid"><label>Transaction type<select defaultValue="buyer-offer"><option value="buyer-offer">Buyer offer</option><option value="listing">Listing</option><option value="new-construction">Builder / new construction</option><option value="investment">Investment purchase</option></select></label><label>Financing type<select defaultValue="conventional"><option value="unknown">Not confirmed</option><option value="cash">Cash</option><option value="conventional">Conventional</option><option value="fha">FHA</option><option value="va">VA</option><option value="seller-financing">Seller financing</option></select></label></div></div>
          <div className="form-actions"><Link className="btn btn-quiet" href="/">Cancel</Link><button className="btn btn-secondary" type="button">Save mock draft</button><Link className="btn btn-primary" href="/transactions/txn-demo">Create mock transaction →</Link></div>
        </form>
        <aside className="card guidance-card"><span className="section-kicker">Before you continue</span><h2>Start with facts, not assumptions.</h2><p>Accord will keep unknown fields visible. Office defaults and future AI suggestions never become confirmed terms without your review.</p><ul className="plain-list"><li>Mock data stays in this prototype.</li><li>No client account is contacted.</li><li>No storage or AI provider is connected.</li><li>No contract is generated.</li></ul></aside>
      </div>
    </Shell>
  );
}
