'use client';
import { useState } from 'react';
import { mockOpportunity } from '@/lib/opportunity';
import { mockPackageForms } from '@/lib/mockData';

export function PrepareWorkspace(){
 const [generated,setGenerated]=useState(false);
 return <div className="prepare-page"><section className="card prepare-summary"><div className="prepare-score"><strong>82%</strong><span>ready</span></div><div><span className="section-kicker">Accord prepared the work</span><h2>Welker buyer offer</h2><p>Most of the package is ready. Two facts need your attention before approval.</p></div><span className="status warn">2 blockers</span></section><div className="prepare-grid"><section className="card blockers-card"><div className="section-heading"><div><span className="section-kicker">Only what needs you</span><h2>Resolve two blockers</h2></div></div>{mockOpportunity.missingFactPrompts.map((fact,index)=><label className="blocker-row" key={fact.id}><span><i>{index+1}</i><strong>{fact.question}</strong><small>{fact.reason}</small></span><input placeholder={index===0?'Choose settlement date':'Enter confirmed legal name or mark unknown'}/></label>)}</section><aside className="card ready-card"><span className="section-kicker">Ready now</span><h2>3-form editable package</h2><ul className="plain-list"><li>Utah REPC populated</li><li>Addendum recommended</li><li>Due diligence checklist included</li><li>DocuSign mock connection ready</li></ul></aside></div><section className="card assumptions-card"><span className="section-kicker">Defaults applied</span><h2>Accord used your approved office defaults</h2><div><span>Buyer representation</span><strong>Red Rock Group</strong><span>Financing</span><strong>Conventional</strong><span>Title preference</span><strong>Red Rock Title</strong></div></section><section className="prepare-details"><details><summary>Source evidence and confidence</summary><div>Purchase price · 98% · “The Welkers are offering $875,000.”<br/>Earnest money · 97% · “Earnest money should be $7,500.”</div></details><details><summary>Recommended forms ({mockPackageForms.filter(f=>f.included).length})</summary><div>{mockPackageForms.map(f=><p key={f.id}><strong>{f.name}</strong> — {f.reason}</p>)}</div></details><details><summary>Lookup suggestions</summary><div>Seller ownership verification is available as a future approved lookup. No lookup has run.</div></details><details><summary>E-signature readiness</summary><div>Preferred provider: DocuSign mock. Provider review opens only after package approval.</div></details></section><section className="prepare-action"><div><strong>{generated?'Editable draft package prepared.':'Ready after blockers are resolved.'}</strong><span>Generation is mock-only. No PDF or provider call occurs.</span></div><button className="btn btn-primary btn-large" type="button" onClick={()=>setGenerated(true)}>Generate Editable Draft Package</button></section></div>;
}
