'use client';
import { useRouter } from 'next/navigation';
import { useState } from 'react';

type CaptureMode='live'|'transcript'|'voice'|'forgot'|'upload';
const modes:[CaptureMode,string,string][]=[['transcript','Paste Transcript','Paste a transcript you already have.'],['voice','Quick Voice Recap','Add a short recap after the conversation.'],['forgot','I Forgot to Record','Recover the details you remember.'],['upload','Upload Notes or Document','Add supporting material later.']];

export function StartConversationFlow(){
 const router=useRouter(); const [mode,setMode]=useState<CaptureMode>('live'); const [consent,setConsent]=useState(false); const [text,setText]=useState('');
 const textMode=['transcript','voice','forgot'].includes(mode);
 return <div className="simple-capture"><section className="card capture-focus"><div className="capture-orb" aria-hidden="true"><span>●</span></div><span className="section-kicker">Capture</span><h2>{mode==='live'?'Ready when you are.':'Add what you have.'}</h2><p>Accord will organize everything afterward.</p>{textMode&&<label>{mode==='transcript'?'Transcript':mode==='voice'?'Quick recap':'What do you remember?'}<textarea value={text} onChange={e=>setText(e.target.value)} placeholder="Start with what you know. Accord will identify the people, property, terms, and missing facts."/></label>}{mode==='upload'&&<button className="upload-placeholder" type="button"><strong>Upload notes or document</strong><span>Mock placeholder · nothing will be stored</span></button>}<label className="simple-consent"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/><span><strong>Recording consent confirmed</strong><small>Required only for live capture. Confirm every participant and the current conversation.</small></span></label><button className="btn btn-primary btn-large capture-primary" type="button" disabled={mode==='live'&&!consent} onClick={()=>router.push('/prepare')}>Capture Conversation</button>{mode==='live'&&!consent&&<small className="center-note">Live capture stays blocked until consent is confirmed.</small>}</section><section className="capture-alternatives" aria-label="Other capture methods">{modes.map(([id,label,detail])=><button type="button" className={mode===id?'active':''} aria-pressed={mode===id} onClick={()=>setMode(id)} key={id}><strong>{label}</strong><span>{detail}</span></button>)}</section></div>;
}
